# Generated by Django 2.2.17 on 2021-01-28 01:41

from django.db import migrations, models
import django.db.models.deletion

import wagtail_favicon.models
import wagtail_favicon.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailFaviconSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_theme_color', models.CharField(blank=True, help_text='Hex colour value', max_length=7, validators=[wagtail_favicon.validators.validate_hex])),
                ('app_name', models.CharField(blank=True, help_text='App name for /icon-manifest.json', max_length=128)),
                ('base_favicon_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.BaseImage')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('social_sharing_image', models.ForeignKey(blank=True, help_text='A default image that wil display when a page is shared on social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.BaseImage')),
            ],
            options={
                'verbose_name': 'Favicon',
            },
            bases=(models.Model, wagtail_favicon.models.FaviconRenditions),
        ),
    ]
