# Generated by Django 2.2.17 on 2021-01-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favicon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faviconsettings',
            options={'verbose_name': 'Favicon'},
        ),
    ]
