# Generated by Django 3.1.9 on 2021-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_favicon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faviconsettings',
            name='social_sharing_image',
        ),
        migrations.AlterField(
            model_name='faviconsettings',
            name='app_name',
            field=models.CharField(blank=True, help_text='App name for manifest.json', max_length=128),
        ),
    ]
